import type { NextPage } from 'next'
import Head from 'next/head'
import React, { Fragment } from 'react'
import AboutMe from '@/components/layouts/AboutMe'
import Contact from '@/components/layouts/Contact'
import Education from '@/components/layouts/Education'
import Footer from '@/components/layouts/Footer'
import Header from '@/components/layouts/Header'
import HeroBanner from '@/components/layouts/HeroBanner'
import Project from '@/components/layouts/Project'
import Skills from '@/components/layouts/Skills'

const Homepage: NextPage = () => {
  return (
    <Fragment>
      <Head>
        <title>Yuto Yamakita</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <Header />
      <div className='h-screen md:snap-y md:snap-mandatory md:overflow-y-scroll md:overflow-x-hidden z-0 scrollbar scrollbar-track-gray-500/20 scrollbar-thumb-[#FF8906]/50'>
        <HeroBanner />
        <AboutMe />
        <Skills />
        <Project />
        <Education />
        <Contact />
        <Footer />
      </div>
    </Fragment>
  )
}

export default Homepage
