import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Fragment } from 'react'

import React from 'react'
import Header from '@/components/layouts/Header'

const Homepage:NextPage = () => {
  return (
      <Fragment>
        <Head>
          <title>Yuto Yamakita</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <Header />
        {/* Hero banner */}
        {/* project */}
        {/* education */}
        {/* contact */}
      </Fragment>
  )
}

export default Homepage